### PR TITLE
Fix BedrockAnthropic3ChatModel out of bounds exception

### PR DESCRIPTION
**Pull request by maxjiang153**
Fix BedrockAnthropic3ChatModel handle AnthropicChatResponse out of bounds exception when response content is empty.

see: https://github.com/spring-projects/spring-ai/issues/757

### CODE REVIEW

**Comment by maxjiang153** [comment]
re-implement with: https://github.com/spring-projects/spring-ai/pull/813

**Comment by markpollack** [comment]
Fixed, please reopen if other issues are encounterd.

**Comment by maxjiang153** [comment]
Will this PR be considered individually or combined with  https://github.com/spring-projects/spring-ai/pull/813?

**Comment by markpollack** [comment]
sorry, I thought I merged this.  We very much appreciate the other PR, it is a huge help but also we need to really sit down and digest it all.   So I will merge this now and #813 will be done in another step.

**Pull request closed without merging**
