### PR TITLE
Implement CassandraChatMemory

### PR DESCRIPTION
**Pull request by michaelsembwever**
And, fix initialize-schema docs and so that it actually works.

In action here: https://github.com/datastax/ai-agent-java/blob/mck/step-1-new-chat-model/src/main/java/com/datastax/ai/agent/history/AiAgentSession.java

### CODE REVIEW

**Comment by tzolov** [comment]
This is really cool! Thanks @michaelsembwever 

Let me know if stumble on some design flows with simplistic ChatMemory interface.

**Comment by michaelsembwever** [comment]
@tzolov ready for review.

Second commit is refactoring of `CommonVectorStoreProperties` to what i believe is a better package location.

**Comment by tzolov** [comment]
Thanks @michaelsembwever 
LGTM. you've forgotten to add the CassandraAutoConfiguration to the AutoConfiguration.imports. But I will fix it during the merge. 

FYI, after M2, we will explore how to implement a "generic" Spring Data Chat Memory support that might affect your impl. as well. 
Anyway, this is the first persistent chat memory implementation! :)

**Comment by tzolov** [comment]
Rebased, squashed and merged at 4aacab020b2fa6932ac3a69433a60c282eec617b

**Pull request closed without merging**
