### PR TITLE
Add OpenAI Stream Client implementation

### LINKED ISSUE #116: Stream support in `AiClient`
**Context**

Applications using AI often use a UI that generates text little by little in a stream instead of outputting texts all at once. The current spring-ai `AiClient` does not support stream output.

**Expected Behavior**

I hope that `generateStream` method will be added to `AiClient`. As for the return value, `Flux<AiResponse>` is promising, but if you want to avoid dependence on reactor, you can also consider the JDK standard `Flow.Publisher<AiResponse>`.

For example, openai-java used in `OpenAiClient` uses `Flowable`. This can be converted to `Flux` or `Flow.Publisher`.

https://github.com/TheoKanning/openai-java/blob/650d76b87a3246a52247b231f8d47f994ae63020/service/src/main/java/com/theokanning/openai/service/OpenAiService.java#L150

This is a little off topic, but openai-java uses outdated RxJava2 and has an unnecessary number of dependencies (e.g. kotlin sdk). Since spring-ai does not use all OpenAI APIs, I think it is better to have an in-house OpenAI client that implements only the minimum API with `WebClient` that supports the streaming.

### PR DESCRIPTION
**Pull request by JM-Lab**
- Add OpenAI Stream Client implementation.
- Add openAiStreamClient test in ClientIT.

Resolves #116

### CODE REVIEW

**Comment by making** [comment]
This PR is very specific to the openai-java implementation and does not resolve #116 .

**Comment by tzolov** [comment]
@JM-Lab as @making pointed out we can not expose proprietary libraries throughout the Spring AI public API. 

Subclassing is not an option either. We need to define a new generic chunk interface or interfaces. 
Also the Spring projects is somewhat biased toward Flux instead of rx.  
Please share your design thoughts, apologies for not providing any guidelines so far.

**Comment by JM-Lab** [comment]
Regarding the feedback from @tzolov, the development was revisited.
OpenAiStreamClient has been re-implemented to directly adhere to the latest Request/Response specifications of OpenAI's Chat Completion API.
Using Flux, the existing 'generate' method was re-implemented, and the 'generateStream' method was added.

The commit details are as follows:

- Add the latest Request and Response Classes of OpenAI's Chat Completion API
- Add the spring-boot-starter-webflux dependency
- Implement the AiStreamClient interface extending AiClient
- Implement OpenAiStreamClient using Reactor Flux

If you have any additional inquiries or recommendations, please don't hesitate to reach out.

**Comment by tzolov** [comment]
Rebased, squashed and merged at 8139af468e9e3e8ba5f1d7f81f7e6e56c1c17fe0
@JM-Lab  thank you for the contribution and expect a follow-up changes as I'm heavily refactoring the chat generation and embedding clients.

**Pull request closed without merging**
