### PR TITLE
fix: ZhiPuAiChatModel createRequest method MediaContent

### LINKED ISSUE #1157: ZhiPu AI use ChatClient setting defaultSystem error
image
image

### PR DESCRIPTION
**Pull request by lwgCodePlus**
ZhiPuAiChatModel  UserMessage  handle error issues
Fixes #1157 #1173

### CODE REVIEW

**Comment by markpollack** [comment]
@lwgCodePlus it isn't clear from the support issues if this PR resolves what has been observed in testing.  Can you confirm?

**Comment by markpollack** [comment]
@lwgCodePlus I believe this has been fixed by https://github.com/spring-projects/spring-ai/pull/1163  Can you verify please?

**Comment by markpollack** [comment]
@mxsl-gr is this PR still relevant?

**Comment by lwgCodePlus** [comment]
I tested it, it's been fixed, this pr doesn't make sense

**Comment by lwgCodePlus** [comment]
I tested it, it's been fixed, this pr doesn't make sense

**Pull request closed without merging**
