### PR TITLE
Use MessageType.FUNCTION for FunctionMessage

### PR DESCRIPTION
**Pull request by yarisvt**
Change the MessageType to FUNCTION in FunctionMessage

### CODE REVIEW

**Comment by yarisvt** [comment]
Hi @tzolov, I was playing around with OpenAI and I created a custom function to retrieve some data from a JSON file to use as a database to match against user input. I figured that it worked correctly when I used the `MessageType.FUNCTION` instead of  `MessageType.SYSTEM`.

E.g.

database.json:
```json
[
  {
    "idCar": "<private-id>",
    "carModel": "Kia Sorento 1.6 T-GDi AT6 Hybrid ComfortLine 5zits 5d 169kW",
  },
  {
    "idCar": "<private-id>",
    "carModel": "Kia Sorento 1.6 T-GDi AT6 Hybrid DynamicLine 7zits 5d 169kW",
  },
  {
    "idCar": "<private-id>",
    "carModel": "Kia Sorento 1.6 T-GDi AT6 Hybrid DynamicPlusLine 7z 5d 169kW",
  },
]
```

System prompt:
```text
You are an employee of a car leasing company whose daily task is to make lease offers based on a quote from a car dealer.
Your job is to determine which car model is on the car dealer quote. Before you determine what car model is on the car dealer quote, you will
call the function 'carModelFunction' to get an overview of available car models. The overview is in format:
{format}.
```

User prompt
```text
What car model is present on this quote from a car dealer?
The quote is written in {language}.

QUOTE:
{quote}
                
{format}
```
with format being:
```java
public record CarModel(String idCar, String carModel) {}
```

I have set it up like this (left the Prompt formatting out)
```java
ChatResponse response = chatClient.call(new Prompt(List.of(systemMessage, userMessage),
                                                         OpenAiChatOptions.builder()
                                                                          .withModel("gpt-4-turbo-preview")
                                                                          .withFunction("carModelFunction")
                                                                          .build()));
```

The `carModelFunction` function just returns the content of `database.json`

I use the following quote:
```text
Dit is een Kia Sorento PHEV Edition 1.6 T-GDi Plug-in Hybrid AT6 AWD (A). Een hele mooie auto
```

When `MessageType.SYSTEM` is used, I get the following response:
```json
{
    "carModel": "Sorento",
    "idCar": ""
}
```

While when using `MessageType.FUNCTION`, I get the following response:
```json
{
    "carModel": "Kia Sorento 1.6 T-GDi AT6 PHEV 4WD Edition 5d 195kW",
    "idCar": "<private-id>"
}
```

So, when `MessageType.FUNCTION` is used, I get the actual data that is present in `database.json`, while I get a ChatGPT generated answer when `MessageType.SYSTEM` is used.

**Comment by tzolov** [comment]
@yarisvt , thank you for the feedback. 

Are you using OpenAI function calling as documented in our reference: https://docs.spring.io/spring-ai/reference/0.8-SNAPSHOT/api/clients/functions/openai-chat-functions.html
Or some custom implementation?

**Comment by yarisvt** [comment]
@tzolov I indeed use the OpenAI function calling as documented in the reference.

**Comment by tzolov** [comment]
@yarisvt, strange not sure why our ITs tests didn't catch this. 

I will merge your PR but can you please provide some sample to reproduce it so i can update our ITs.

**Comment by yarisvt** [comment]
@tzolov Example: https://github.com/yarisvt/spring-ai-function-example

**Comment by yarisvt** [comment]
I have tested some more with the above example, and I actually get the same result when either `MessageType.SYSTEM` or `MessageType.FUNCTION` is used. However when I use version `0.8.0` I get the incorrect result. So it looks like something else in the `0.8.1-SNAPSHOT` version actually fixed the problem

**Pull request merged**
