### PR TITLE
Add support for Redis vector store

### PR DESCRIPTION
**Pull request by jruaux**
This PR adds supports for Redis vector search.

### CODE REVIEW

**Comment by tzolov** [comment]
Hi @jruaux , thank you for the contribution. 
I will have a deeper look shortly, but wanted to let you know that I appreciate the extra effort in implementing the filters as well ;)

**Comment by jruaux** [comment]
@tzolov Happy to contribute to the project. Please let me know if anything needs work

**Comment by markpollack** [comment]
Hi @jruaux.  Thanks so much.  I just squashed and added some Javadoc.  Great job.

Closed in a232166cf35bb0b83d11db1f1c824183a210cb4f

**Comment by tzolov** [comment]
Hi @jruaux , 
just noticed the Redis auto-configuration (like https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure) is missing.
Without an auto-configuraiton the [spring-ai-starter-redis](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-starters/spring-ai-starter-redis) boot starter is usless.

Please let me know if you have time and interest to contribute the missing auto-configuration. You can consult the other vectors' auto configuration impls for example or we can arrange a peer session ;)
Otherwise we should remove the redis starter for until the auto-conf is implemented.

**Comment by jruaux** [comment]
Hi @tzolov, there is a `RedisVectorStoreAutoConfiguration` under https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/redis

Is that what you were looking for?

**Comment by tzolov** [comment]
Sorry @jruaux, i overlooked it.Indeed everything is OK. Thank you again

**Pull request closed without merging**
