### PR TITLE
PgVectorStore keeps creating an index on embedding column even if an index already exists

### PR DESCRIPTION
**Pull request by iAMSagar44**
Providing a fix for this issue - https://github.com/spring-projects/spring-ai/issues/611

### CODE REVIEW

**Comment by tzolov** [comment]
Hi @iAMSagar44 , thanks for the submission. 
Have you run the pgvector integration tests? 
`./mvnw clean install -pl vector-stores/spring-ai-pgvector-store -Pintegration-tests`

**Comment by tzolov** [comment]
I believe you've missed the index name : https://www.postgresql.org/docs/current/sql-createindex.html
I will handle it before the merge.
Thank you again for the contribution, just please make sure to run all tests next time before submitting the pr.

**Comment by tzolov** [comment]
Rebase, add missing index name, squash and merge at 773b7bd3cacb3c644b2fcb67bf6355a463c47bf7

**Comment by iAMSagar44** [comment]
> Hi @iAMSagar44 , thanks for the submission. 
> 
> Have you run the pgvector integration tests? 
> 
> `./mvnw clean install -pl vector-stores/spring-ai-pgvector-store -Pintegration-tests`
> 
> 
> 
> ```
> 
> Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "ON"
> 
>   Position: 28
> 
> ```
> 
> 

Hi @tzolov,

Thanks for pointing this out.
I did run an integration test after making the change, but I might have made a mistake on running the test on an existing package (I think I missed the 'clean install' maven command).
I will ensure this doesn't happen again.

**Pull request closed without merging**
