### PR TITLE
Add Moonshot model client

### PR DESCRIPTION
**Pull request by mxsl-gr**
Hi, this PR is add `Moonshot` model client and has passed unit testing.
I can provide my api_key if needed for testing

the  PR content:

- Moonshot AI model client
- unit test
- spring starter
- chat client documents
﻿

`Moonshot` is a popular LLM in China Mainland recently, the link: [Moonshot](https://platform.moonshot.cn/docs/api-reference)

### CODE REVIEW

**Comment by mxsl-gr** [comment]
Add autoconfigure unit test and squash commits.

**Comment by mxsl-gr** [comment]
Hi @markpollack , sorry to bother you, I noticed there have been some recent refactorings to the code. Do these model client PRs also need to be adjusted accordingly?

**Comment by mxsl-gr** [comment]
@tzolov hi, sorry to bother you, it seems Mark is on vacation...
this PR has completed the refactoring, has been squashed and force pushed again, and also added support for function calls.

**Comment by mxsl-gr** [comment]
I sent the API keys for `Moonshot` and others model provider's key to Mark via email before. 
I'm not sure if Mark has shared them with you. 
If you need them, please contact me and I can provide them again, including `QianFan` on https://github.com/spring-projects/spring-ai/pull/751 and `DeepSeek` https://github.com/spring-projects/spring-ai/pull/702

**Comment by markpollack** [comment]
Hello, I apologize but was pulled into other areas of work.  I will be going through this today.  Thanks again.

**Comment by mxsl-gr** [comment]
> Hello, I apologize but was pulled into other areas of work. I will be going through this today. Thanks again.

Wow, welcome back,  I just checked the emails, and the API keys for `Deepseek` and `Moonshot` were sent before. 
I noticed that i haven't sent the API key for `Qianfan`, so I just sent you a new email with it.
but the balance in it is not very much, but it should be enough for testing, If the balance is insufficient, please contact me.

**Comment by markpollack** [comment]
Merged in d5b8123e60411f5d4a2cd5ee9eaf31f92a72c88c  made a few minor changes.  Note that `BeanOutputParser` is deprecated, so the tests should use `BeanOutputConverter` and other similar `OutputConverter` classes.

The api keys you sent worked!

**Pull request closed without merging**
