### PR TITLE
Update property precedence in documentation

### PR DESCRIPTION
**Pull request by jitokim**
Update documentation for property override precedence in ChatModel and EmbeddingModel configurations.

### CODE REVIEW

**Comment by tzolov** [comment]
Thanks @jitokim

**Comment by markpollack** [comment]
The changes to not seem correct, there are dedicated configuration prefix for the embedding models, see `OpenAiEmbeddingProperties`.  What is the intention here?  Embedding can have a different URL than chat, they have separate `@ConfigurationProperties` classes.

**Comment by jitokim** [comment]
> The changes to not seem correct, there are dedicated configuration prefix for the embedding models, see `OpenAiEmbeddingProperties`. What is the intention here? Embedding can have a different URL than chat, they have separate `@ConfigurationProperties` classes.

It seems to be understood as a comment on this note. 

https://github.com/spring-projects/spring-ai/blame/560315ccfc4ac823d2d7c3cc2a1983e22e58992e/spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/openai-embeddings.adoc#L110

The intention is that when using both the Embedding Model and the Chat Model together, the properties can be overridden individually.

Please let me know if there is any misunderstanding. Thank you.

**Comment by jitokim** [comment]
@markpollack  
Thanks for review.
I re-read the Chat Model documentation and understood your comment. I'll revise it soon.

**Pull request merged**
