### PR TITLE
Add AWS OpenSearch AutoConfiguration

### PR DESCRIPTION
**Pull request by eddumelendez**
Currently, in order to use an OpenSearch instance provided by AWS, additional steps are needed. This commit introduces the required configuration.

It's tested using Testcontiners and LocalStack.

Question:
* Should a starter be added? Maybe `spring-ai-aws-opensearch-store-spring-boot-starter`
If the answer is yes, then I can update the documentation later.

### CODE REVIEW

**Comment by tzolov** [comment]
@eddumelendez, 
valuable improvement. 

> Should a starter be added? Maybe `spring-ai-aws-opensearch-store-spring-boot-starter`
If the answer is yes, then I can update the documentation later.

You mean `spring-ai-aws-opensearch-store-spring-boot-starter` in addition to the existing `spring-ai-opensearch-store-spring-boot-starter` ?
This makes sense. 

Would you add it in this PR or separate one?

**Comment by eddumelendez** [comment]
Hi @tzolov. Yes, in addition to the existing one.

I have updated the PR adding the new starter and updating the docs.

**Comment by tzolov** [comment]
Thanks @eddumelendez

**Comment by tzolov** [comment]
rebased, squashed and merged at d276d17c1f546ec4a2be933e40c786ded603a6c9

**Pull request closed without merging**
