### PR TITLE
Add comment in MessageType for readability

### LINKED ISSUE #972: Add comment in MessageType for readability
When I first saw MessageType, I didn't understand easily what each value meant. So I wrote an comment by referring to the description of each implementation, which I thought would be easy for beginners to understand, so I wrote it. I'd appreciate it if you could review it.

please see #1000

### PR DESCRIPTION
**Pull request by devholic22**
* Add comment in MessageType for readability
* fix enum comment grammar

resolved #972

### CODE REVIEW

**Comment by tzolov** [comment]
Thank you for the improvement @devholic22 
Could you please resolve the formatting issue by running the `./mvnw spring-javaformat:apply javadoc:javadoc -Pjavadoc` and then squash the 3 commits.

**Comment by devholic22** [comment]
> Thank you for the improvement @devholic22 Could you please resolve the formatting issue by running the `./mvnw spring-javaformat:apply javadoc:javadoc -Pjavadoc` and then squash the 3 commits.

Thanks for your advice. But even if I keep running the commands you mentioned, I won't get a file that changes. Is there any other way? If there is, I will apply it right away.
Actually, the second commit also applied `./mvnw spring-javaformat:apply.`

there is my git status after your command apply.
스크린샷 2024-06-28 오후 7 06 40

**Comment by devholic22** [comment]
@tzolov The cause code is `MongoDBAtlasFilterExpressionConverter`. I fixed this class comment :)

**Comment by tzolov** [comment]
yeh, sorry. i've fixed the other error in https://github.com/spring-projects/spring-ai/commit/c09286eedfff170c733c9ed3398f08d87dcdc7ba

Could you please rebase your branch, please use `git pull -r upstream main` not merge, resolve the eventual conflicts and squash the result into a single commit.

**Comment by devholic22** [comment]
Did I correct it well as you intended? I would appreciate it if you could check it :)

**Comment by tzolov** [comment]
I still can see 2 commits? Did you squashed all commits?

**Comment by devholic22** [comment]
> I still can see 2 commits? Did you squashed all commits?

I squashed my commits using `git rebase` command :)

**Comment by markpollack** [comment]
There are still 4 commits in this PR.  I suggest you make a new PR with one commit that contains the changes you made the the file.

**Comment by devholic22** [comment]
> There are still 4 commits in this PR. I suggest you make a new PR with one commit that contains the changes you made the the file.

I understand. you can check in [new PR](https://github.com/spring-projects/spring-ai/pull/1000).  
Next time, I will squash the commits as you say. I'm sorry for the inconvenience.

**Comment by ThomasVitale** [comment]
@devholic22 can this PR be closed since the change has been delivered via https://github.com/spring-projects/spring-ai/pull/1000?

**Pull request closed without merging**
