### PR TITLE
Adds Spring boot starter for Neo4j Store

### LINKED ISSUE #114: Add Auto-Configurations and Boot starters for all Vector Store implementations
Most Spring-ai vector store implementations already have a proper [boot auto-configurations](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore) in place. 
Create the corresponding Spring Boot Starters under the [spring-ai-spring-boot-starters](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-starters) and update the VectorStore's `README.md` with both starter usage instructions.

- [x] [Milvus Vector Store](https://github.com/spring-projects/spring-ai/tree/main/vector-stores/spring-ai-milvus-store), using the [milvus auto-configure](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/milvus)
- [x] [Chroma Vector Store](https://github.com/spring-projects/spring-ai/tree/main/vector-stores/spring-ai-chroma), using the [chroma auto-configure](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/chroma)
- [x] [PgVector Vector Store](https://github.com/spring-projects/spring-ai/tree/main/vector-stores/spring-ai-pgvector-store), using the [pgvector auto-configure](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/pgvector)
- [x] [Pinecone Vector Store](https://github.com/spring-projects/spring-ai/tree/main/vector-stores/spring-ai-pinecone), using the [pinecone auto-configure](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/pinecone)
- [x] [Azure Vector Store](https://github.com/spring-projects/spring-ai/tree/main/vector-stores/spring-ai-azure), using the [azure vector store auto-configure](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/azure)
- [x] [Weaviate Vector Store](https://github.com/spring-projects/spring-ai/tree/main/vector-stores/spring-ai-weaviate) - using the [weaviate vector store auto-configure](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore)
- [x]  [Redis Vector Store](https://github.com/spring-projects/spring-ai/tree/main/vector-stores/spring-ai-redis) - using the [redis vector store auto-configure](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/redis)
- [x] [Neo4j Vector Store](https://github.com/spring-projects/spring-ai/tree/main/vector-stores/spring-ai-neo4j-store) - using the [neo4j auto-config](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/neo4j)

### PR DESCRIPTION
**Pull request by Sohardh**
Fix #114

### CODE REVIEW

**Comment by markpollack** [comment]
Thanks!  :bowing_man:   Merged as 5b46361373f00a19c4a8dd3c4740bb8c3d0ea843

**Comment by tzolov** [comment]
@markpollack @Sohardh there is not Auto-configuration for the Neo4j. Without an auto-config there can't be spring boot starter either. 
So what exactly is this PR about and why is it merged?

**Comment by King-Chau** [comment]
> @markpollack @Sohardh there is not Auto-configuration for the Neo4j. Without an auto-config there can't be spring boot starter either. So what exactly is this PR about and why is it merged?

I have the same question. Why there is not Neo4jAutoConfiguration? Does this starer work?

**Comment by tzolov** [comment]
@King-Chau  No this was a mistake and I've removed the starter, Btw same mistake applies for the Redis vector store. 

If interested, please fill free to contribute auto-configuration and a starter: https://github.com/spring-projects/spring-ai/issues/114

**Comment by tzolov** [comment]
Thanks to @King-Chau we have a [neo4j-autoconifugraiton](https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/neo4j).
I will see if i can (re)introduce this PR and adjust its pom to include the above autoconfig.

**Comment by tzolov** [comment]
squashed, rebased and merged at: 5ba78c2feaa3732d9e934a441c9bcf594126e9d2

**Comment by tzolov** [comment]
squashed, rebased and merged at: https://github.com/spring-projects/spring-ai/commit/5ba78c2feaa3732d9e934a441c9bcf594126e9d2

**Pull request closed without merging**
