### PR TITLE
fix:resolve NPE error when using OpenAI embedding model

### PR DESCRIPTION
**Pull request by hambuger**
Resolves issue: #1152

### CODE REVIEW

**Comment by ThomasVitale** [comment]
Thanks for the PR! I have also raised this bug in https://github.com/spring-projects/spring-ai/issues/1152 and opened this PR yesterday https://github.com/spring-projects/spring-ai/pull/1153

**Comment by tzolov** [comment]
Thank you for catching this @hambuger 
I believe the 9a8a133d9388e020109bb4f108ac22520760e00f commit resolves it?

**Comment by tzolov** [comment]
Resolved by 9a8a133d9388e020109bb4f108ac22520760e00f
@hambuger feel free to re-open the PR if the issue is still present.

**Comment by hambuger** [comment]
> Resolved by 9a8a133d9388e020109bb4f108ac22520760e00f
> 
> @hambuger feel free to re-open the PR if the issue is still present.

It is ok. I just provided another solution that I think is reasonable.

**Pull request closed without merging**
