### PR TITLE
:fix: constructor error messages

### PR DESCRIPTION
**Pull request by Grogdunn**
More exhaustive error message when creating a Document.

### CODE REVIEW

**Comment by tzolov** [comment]
Thanks @Grogdunn, 
could you please fix the formatting issue (run `./mvnw spring-javaformat:apply`) and then squash the commits.

**Comment by Grogdunn** [comment]
ok, I'll do, but the problem are on a "untouched by me" file :) vector-stores/spring-ai-mongodb-atlas-store/src/main/java/org/springframework/ai/vectorstore/MongoDBAtlasFilterExpressionConverter.java

**Comment by tzolov** [comment]
Ah i'm sorry i've fixed this in https://github.com/spring-projects/spring-ai/commit/c09286eedfff170c733c9ed3398f08d87dcdc7ba

**Comment by tzolov** [comment]
Thanks again @Grogdunn

**Pull request merged**
