### PR TITLE
Mistral AI model support 

### PR DESCRIPTION
**Pull request by ricken07**
Mistral AI develops open-source and secure generative artificial intelligence models.

Mistral is a powerful and fast model, adaptable to many use cases.

Looking at the number of models supported by Spring AI, we'd like it to support Mistral too.

### CODE REVIEW

**Comment by ricken07** [comment]
I'm working on implementing a client for chat completions and streaming support.

**Comment by tzolov** [comment]
@ricken07 thanks for dedicating time and effort for exploring this area!
 
Unfortunately something is very wrong with your branch and it is impossible to review it as it is.

Pleas rebase your code to the top of upstream/main, **without merging** the main! 
E.g. something like `mvn pull -r upstream main` and resolve the conflicts. 
It might be easier to copy your code in a new PR on top of upstream/main.

**Comment by ricken07** [comment]
@tzolov thanks for your feedback.

I've copied my code into a new PR "Support for Mistral AI" on top of upstream/principal

**Comment by tzolov** [comment]
Replaced by https://github.com/spring-projects/spring-ai/pull/369

**Pull request closed without merging**
