### PR TITLE
Implement KotlinModule for JSON schema generation

### PR DESCRIPTION
**Pull request by devcrocod**
### Issue

#1667 

---

- Implemented `com.github.victools.jsonschema.generator.Module` for Kotlin. This adds support for generating JSON schemas from Kotlin classes by leveraging Kotlin reflection. The module handles nullability, default values, and required properties based on Kotlin's types

- Added `kotlin-reflect` dependency
- Updated Kotlin version to 2.0.21

### CODE REVIEW

**Comment by markpollack** [comment]
Looks like a great contribution, Sebastian is on PTO this week, so he can review next week when he is back.  Thanks!

**Comment by markpollack** [comment]
@sdeleuze can you take a look as time permits please

**Review by sdeleuze — CHANGES_REQUESTED** [review]
Looks good, thanks for this contribution, please just remove the Kotlin version bump to 2.0.21 as we need to keep a Kotlin 1.9 baseline with Boot 3.x. I will update the documentation accordingly once merged.

**Comment by tzolov** [comment]
Thank you @devcrocod for the contribution and @sdeleuze for reviewing it!

**Comment by tzolov** [comment]
rebased , squashed and merged at 756a9dcc08fbbb0173ddba9e47e8b4f6bec3339f

**Pull request closed without merging**
