### PR TITLE
Fix npe ollama streaming image 1459

### PR DESCRIPTION
**Pull request by mudabirhussain**
Fixed the null pointer exception.

### CODE REVIEW

**Comment by tzolov** [comment]
@mudabirhussain is this issue related to ToolCall or multimodality support?

**Comment by mudabirhussain** [comment]
> @mudabirhussain is this issue related to ToolCall or multimodality support?

ToolCall.

**Comment by tzolov** [comment]
> ToolCall.
Then i'm not sure the issue name `streaming image 1459` should mean?

Currently Ollama doesn't support streaming ToolCalls: https://github.com/ollama/ollama/issues/5796

Can you provide some ITs to reproduce the problem this PR solves?

**Comment by mudabirhussain** [comment]
> > ToolCall.
> > Then i'm not sure the issue name `streaming image 1459` should mean?
> 
> Currently Ollama doesn't support streaming ToolCalls: [ollama/ollama#5796](https://github.com/ollama/ollama/issues/5796)
> 
> Can you provide some ITs to reproduce the problem this PR resolves?

go to this link for more details regarding the issue: https://github.com/spring-projects/spring-ai/issues/1459

**Comment by tzolov** [comment]
I see, thank you @mudabirhussain

**Comment by markpollack** [comment]
merged in 209082665637bef45691f3c0390f08cd405a22ba

**Comment by markpollack** [comment]
thanks @mudabirhussain

**Pull request closed without merging**
