### PR TITLE
Do not add empty user text on chat memory

### PR DESCRIPTION
**Pull request by DHKIM-0511**
close https://github.com/spring-projects/spring-ai/issues/1601

someone did not want add empty user text on chat memory

so, I fix chat advisor to not add message when user text is empty

### CODE REVIEW

**Comment by ThomasVitale** [comment]
Thanks for submitting this PR! This shouldn't be needed anymore since we introduced null-safety for ChatClient and Advisor APIs, and removed the default empty user text. The user message is now required and it will never be null or empty in the context of an Advisor.

**Comment by DHKIM-0511** [comment]
> Thanks for submitting this PR! This shouldn't be needed anymore since we introduced null-safety for ChatClient and Advisor APIs, and removed the default empty user text. The user message is now required and it will never be null or empty in the context of an Advisor.

Oh, I see. I'm also curious about other possible solutions—would it be possible to check the commit history to see how it was implemented? Thanks for your kind response!

**Comment by ThomasVitale** [comment]
Yes, of course! Most changes are in this PR: https://github.com/spring-projects/spring-ai/pull/1651

**Comment by ThomasVitale** [comment]
@DHKIM-0511 we have an open discussion about making the logic of identifying a user message more flexible, while still ensuring internal consistency. If you have some use cases or ideas related to that, feel free to share them in https://github.com/spring-projects/spring-ai/issues/1665 Thanks!

**Comment by DHKIM-0511** [comment]
Looking at the PR, I realized I missed a few lines of code. I understand now that the feature is no longer needed. I’ll also consider the issue you mentioned. Thanks!

**Pull request closed without merging**
