### PR TITLE
Change flatten pom config

### PR DESCRIPTION
**Pull request by markpollack**
* root project pom now sets <dependencyManagement>remove</dependencyManagement>
* spring-ai-bom pom flatten plugin added with <dependencyManagement>keep</dependencyManagement>

### CODE REVIEW

**Comment by jvalkeal** [comment]
lgtm

**Comment by laglangyue** [comment]
Please note the indentation of XML

**Comment by markpollack** [comment]
@laglangyue what is wrong with the indentation? It looks gtm...

**Comment by markpollack** [comment]
I've merged it, but will leave the issue open to discuss.

**Pull request closed without merging**
