### PR TITLE
Feat: Add Watsonx.ai Embedding Model

### PR DESCRIPTION
**Pull request by PabloSanchi**
Add Watsonx embedding model

### CODE REVIEW

**Comment by PabloSanchi** [comment]
I updated the embedding model following the new core interface requirements.

**Comment by PabloSanchi** [comment]
@tzolov is it possible to merge it? it would make me a giant favour as I will be needing it for a project :)
Thanks

**Comment by markpollack** [comment]
will get to it soon.

**Comment by markpollack** [comment]
Thanks again!  Merged in 035036c7f20bbfcd85312c06e7dd0fbed56d4f71

**Pull request closed without merging**
