### PR TITLE
Adding SAP HanaDB as a vector store.

### PR DESCRIPTION
**Pull request by rahulmitt**
Thank you for taking time to contribute this pull request!
You might have already read the [contributor guide][1], but as a reminder, please make sure to:

- [x] * Sign the [contributor license agreement](https://cla.pivotal.io/sign/spring)
- [ ] * Rebase your changes on the latest `main` branch and squash your commits
- [x] * Add/Update unit tests as needed
- [x] * Run a build and make sure all tests pass prior to submission

### CODE REVIEW

**Comment by sobychacko** [comment]
@rahulmitt It looks like you contributed the original implementation for the HanaDB vector store in Spring AI. Do you have insights into how we can test this vector store implementation? 

For example, we are trying to run this test. https://github.com/spring-projects/spring-ai/blob/main/vector-stores/spring-ai-hanadb-store/src/test/java/org/springframework/ai/vectorstore/hanadb/HanaCloudVectorStoreIT.java#L52.

Is there a way to create a test Hana environment and retrieve those credentials?

Thanks!

**Comment by markpollack** [comment]
That documentation is outdated.  I signed up via the web and received an email - i can see a database explorer etc so something is working, but I don't see any way to get creds to use to access remotely.

my welcome email is 

"Thank you for your interest in the SAP HANA Cloud basic trial
 	
Dear Mark,

You’re about to learn how to build and deploy intelligent data applications at scale. Here are your account details to begin setting up your free trial account."

**Comment by rahulmitt** [comment]
That's terrible Mark. Let me see if I can get something over the weekend please.

**Comment by markpollack** [comment]
ok great.  I DM'd you on linked in - ping me there please.

**Pull request closed without merging**
