### PR TITLE
Feat: Add Typesense vector store adapter

### PR DESCRIPTION
**Pull request by PabloSanchi**
This PR adds support for Typesense vector store to Spring AI.
More details about Typesense can be found [here](https://typesense.org/).

### CODE REVIEW

**Comment by tzolov** [comment]
Hey @PabloSanchi , thank you for the contribution. 
Have not used the Typesense but like the fact it is open sourced and can be tested in docker containers. 
Regarding the later could you please add IT tests for the Typesense auto-configuration. 
Also rename the `spring-ai-typesense` module and pom artifact to `spring-ai-typesense-store` instead. 
and the boot-starter module `spring-ai-starter-typesense` to `spring-ai-starter-typesense-store` and the artifact from `spring-ai-typesense-spring-boot-starter` to `spring-ai-typesense-store-spring-boot-starter`

**Comment by PabloSanchi** [comment]
Now it should be fixed, I added the tests and renamed the class, I can see that there are conflicts though

**Comment by PabloSanchi** [comment]
I will fix it as soon as I can :)

**Comment by tzolov** [comment]
Thank you again @PabloSanchi ! Good stuff. 
I made few small adjustments and it is ready to merge.

**Comment by tzolov** [comment]
Rebased, squashed and merged at 3e2ed8b9bf78f516b97949396292276132269a25

**Pull request closed without merging**
